FROM nvidia/cuda:11.3.1-base-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    ffmpeg \ 
    && rm -rf /var/lib/apt/lists/* 
RUN python3 -m pip install --upgrade pip  \
    pip install git+https://github.com/openai/whisper.git@v20230314 \
    pip install pytube omegaconf \
    pip install --no-cache-dir torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
