FROM nvidia/cuda:11.3.1-base-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    ffmpeg \ 
    curl\
    && rm -rf /var/lib/apt/lists/* 
RUN curl --create-dirs -o /root/.cache/whisper/large.pt https://openaipublic.azureedge.net/main/whisper/models/81f7c96c852ee8fc832187b0132e569d6c3065a3252ed18e56effd0b6a73e524/large-v2.pt 
RUN python3 -m pip install --upgrade pip  \
    pip install git+https://github.com/openai/whisper.git@v20230314 \
    pip install pytube omegaconf numba\
    pip install --no-cache-dir torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
