FROM nvidia/cuda:11.3.1-base-ubuntu20.04
RUN apt-get update && apt-get install -y \
    git \
    vim \
    ffmpeg \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* 
COPY requirements.txt /tmp/
RUN python3 -m pip install --upgrade pip  \
    pip install --no-cache-dir --requirement /tmp/requirements.txt  \
    pip install --no-cache-dir torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
