FROM jrottenberg/ffmpeg:3.2.19-ubuntu2004
RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    wget \
    && rm -rf /var/lib/apt/lists/* 
COPY requirements.txt /tmp/
RUN python3 -m pip install --upgrade pip  \
    pip install --no-cache-dir --requirement /tmp/requirements.txt  \ 