repositories:

- name:  apache-airflow
  url: https://airflow.apache.org
- name: incubator
  url: https://charts.helm.sh/incubator
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: minio
  url: https://charts.min.io/

releases:
  - name: airflow                           
    namespace: airflow                      
    labels:                                  
      app: airflow
    chart: apache-airflow/airflow
    version: 1.5.0
    needs:
      - airflow-namespace
    values:
      - executor: KubernetesExecutor
        # extraEnvFrom: 
        #   - secretRef:
        #       name: airflow-connections
        #   - configMapRef:
        #       name: airflow-variables
        dags:
          gitSync:
            enabled: true
            repo: https://github.com/mohittalele/airflow-dag.git
            branch: feature/airflow-tutorials
            subPath: DAG
        logs:
          persistence:
            enabled: true
            size: 10Gi

  - name: airflow-namespace                                            
    labels:                                  
      app: airflow
    chart: incubator/raw
    namespace: airflow
    values:
      - resources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: airflow

  - name: rabbitmq
    labels:                                  
      app: rabbitmq
    chart: bitnami/rabbitmq
    version: 9.0.8
    namespace: airflow
    values:
      - auth:
          username: user
          password: password

  - name: minio
    labels:                                  
      app: minio
    chart: minio/minio
    version: 4.0.2
    namespace: airflow
    values:
      - mode: standalone

