db:
  env: development
  driver: ${db.env}_mysql
  user: ${db.env}_omry
  password: secret_in_dev
  additional_key : ${db.env}_additional_key
  vyper_settings:
    tagger:
      tag_frequency: changed
      algorithm: changed
      output_bucket_path: changed