db:
  UDID: ???
  date: ???
  env: stg
  driver: ${db.env}_mysql
  user: ${db.env}_omry
  password: secret_in_dev
  additional_key: ${db.env}_additional_key
  foo:
    zoo: car
    abc: xyz
  jobs:
    - vyper_tag
    - vyper_face_tag
    - vyper_slang_tagger
  vyper_settings:
    tagger:
      tag_frequency: daily
      algorithm: dummy_algo
      input_bucket_path: vyper/${db.UDID}
      output_bucket_path: vyper/${db.date}/${db.UDID}
      airflow_file_path: ???
    slang_word_tagger:
      tag_frequency: daily
      algorithm: dummy_algo
      input_bucket_path: vyper/${db.UDID}
      output_bucket_path: vyper/${db.date}/${db.UDID}/slang_word_tagger
    vyper_face_tag:
      abc:
        xyz:
          - vyper_face_tag
          - vyper_face_tag_array
        foo: bar