db:
  UDID: ???
  date: ???
  env: development
  driver: ${db.env}_mysql
  user: ${db.env}_omry
  password: secret_in_dev
  additional_key: ${db.env}_additional_key
  foo:
    zoo: car
    abc: xyz
  jobs:
    - vyper_tag
    - vyper_face_tag
    - vyper_slang_tagger
