name: ci

on:
  push:
    branches:
      - 'main'
      - 'feature/remove-top-level-code'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   #TODO build from source code from the apache airflow
      #   name: Build and push Airflow
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags:  ${{ secrets.DOCKERHUB_USERNAME }}/airflow:2.5.0v1

      # - name: Build and push Dockerfile.cuda
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.cuda
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu20.04-cuda-base11.3.1-torch1.12:0.1

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.essentia
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/essentia:v1
      
      # - name: Build and push whisper
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.whisper
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu20.04-cuda-base11.3.1-torch1.12-whisper:0.6

      # - name: Build and push scene-tagger
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.scene-tagger
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvidia-cuda-11.8.0-devel-ubuntu22.04-scene-tagger:0.2

      # - name: Build and push scene-tagger vy1.0
      #   id: docker_build_scene_tagger_vy1
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.scene-tagger-vy1.0
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ffmpeg-scene-tagger-vy1.0:0.1

      # - name: Build and push movie-net
      #   id: docker_build_movie_net
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.movienet_tools
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvidia-cuda-10.2-devel-ubuntu18.04-movie-net-tools:0.3

      # - name: Build and push mmaction2
      #   id: docker_mmaction2
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.mmaction2
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvidia-cuda-10.2-devel-ubuntu18.04-mmaction2:0.1
      
      # - name: Build and push sentence-transformers
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.sentence_transformer
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvidia-cuda-11.8.0-devel-ubuntu22.04-sentence_transformer:0.7

      - name: Build and push sentence-transformers-mlserver
        id: docker_build_push_mlserver
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./sentence-transformer-mlsever/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sentence_transformer_mlserver:0.7
