name: ci

on:
  push:
    branches:
      - 'main'
      - 'feature/remove-top-level-code'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   #TODO build from source code from the apache airflow
      #   name: Build and push Airflow
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags:  ${{ secrets.DOCKERHUB_USERNAME }}/airflow:2.4.1v1

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.cuda
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu20.04-cuda-base11.3.1-torch1.12:0.1

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile.essentia
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/essentia:v1
      
      - name: Build and push whisper
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.whisper
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu20.04-cuda-base11.3.1-torch1.12-whisper:0.2