name: ci

on:
  push:
    branches:
      - 'main'
      - 'feature/remove-top-level-code'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        #TODO build from source code from the apache airflow
        name: Build and push Airflow
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/airflow:2.3.3v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile1
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-util:20.04v4