name: Build and Push Whisper Docker Image

on:
  push:
    branches:
      - 'main'
      - 'feature/remove-top-level-code'

env:
  DOCKERHUB_USERNAME:  ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME:  ubuntu20.04-cuda-base11.3.1-torch1.12-whisper
  IMAGE_TAG: 0.3

jobs:
  check-docker-image:
    runs-on: ubuntu-latest
    outputs:
      docker-image-exists: ${{ steps.docker-image-check.outputs.docker-image-exists }}
    steps:
      - name: Check if Docker image exists
        id: docker-image-check
        run: |
          set -e
          curl --head --fail https://hub.docker.com/v2/repositories/${DOCKERHUB_USERNAME}/${IMAGE_NAME}/tags/${IMAGE_TAG}/ >/dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "::set-output name=docker-image-exists::true"
          else
            echo "::set-output name=docker-image-exists::false"
          fi

  build-and-push:
    needs: check-docker-image
    runs-on: ubuntu-latest
    if: ${{ needs.check-docker-image.outputs.docker-image-exists == 'true' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}