name: Build and Push Whisper Docker Image

on:
  push:
    branches:
      - 'main'
      - 'feature/remove-top-level-code'

env:
  IMAGE_NAME: ubuntu20.04-cuda-base11.3.1-torch1.12-whisper
  IMAGE_TAG: 0.3
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  check-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Docker image exists
        run: |
          image_exists=$(curl -sSf https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/${IMAGE_NAME}/tags/${IMAGE_TAG} | jq -r '.name')
          echo "image_exists=$([ "$image_exists" = "$IMAGE_TAG" ] && echo true || echo false)" > $GITHUB_ENV
      - name: Display output
        run: echo $image_exists

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-docker-image
    if: env.image_exists == 'true'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.whisper 
          push: true
          tags: ${DOCKER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}